// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Stavky.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Account Activation Flow")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class AccountActivationFlowFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Account Activation Flow", @"  As a new user who signed up
  I want to see activation instructions with IBAN and pricing
  So that I know how to pay and activate my account

  As an admin
  I want to manually activate user accounts and configure activation settings
  So that I can manage access after receiving bank payments", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AccountActivation.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 10
  #line hidden
#line 11
    await testRunner.GivenAsync("the application is running at \"http://localhost:3000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/AccountActivation.feature.ndjson", 15);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Inactive customer is redirected to activation page from bettings")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("customer")]
        public async global::System.Threading.Tasks.Task InactiveCustomerIsRedirectedToActivationPageFromBettings()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "customer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Inactive customer is redirected to activation page from bettings", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 17
    await testRunner.GivenAsync("I am logged in as an inactive customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
    await testRunner.WhenAsync("I navigate to the bettings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.ThenAsync("I should be redirected to the activation page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
    await testRunner.AndAsync("I should see the activation heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("I should see the monthly price \"40\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync("I should see the yearly price \"360\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("I should see the IBAN section", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Activation page displays locale-specific message")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("customer")]
        public async global::System.Threading.Tasks.Task ActivationPageDisplaysLocale_SpecificMessage()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "customer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activation page displays locale-specific message", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 27
    await testRunner.GivenAsync("I am logged in as an inactive customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 28
    await testRunner.WhenAsync("I navigate to the activation page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("I should see the activation heading", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 30
    await testRunner.AndAsync("I should see the payment instructions message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Activation page has a back to home button")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("customer")]
        public async global::System.Threading.Tasks.Task ActivationPageHasABackToHomeButton()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "customer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Activation page has a back to home button", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 34
    await testRunner.GivenAsync("I am logged in as an inactive customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.WhenAsync("I navigate to the activation page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
    await testRunner.AndAsync("I click the back to home button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.ThenAsync("I should be on the home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Active customer is not shown the activation page")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("customer")]
        public async global::System.Threading.Tasks.Task ActiveCustomerIsNotShownTheActivationPage()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "customer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Active customer is not shown the activation page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.GivenAsync("I am logged in as an active customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
    await testRunner.WhenAsync("I navigate to the activation page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
    await testRunner.ThenAsync("I should be redirected to the bettings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Active customer can access bettings page")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("customer")]
        public async global::System.Threading.Tasks.Task ActiveCustomerCanAccessBettingsPage()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "customer"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Active customer can access bettings page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 47
    await testRunner.GivenAsync("I am logged in as an active customer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.WhenAsync("I navigate to the bettings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
    await testRunner.ThenAsync("I should see the bettings page content", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin can see the activation section in settings")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminCanSeeTheActivationSectionInSettings()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can see the activation section in settings", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 55
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
    await testRunner.ThenAsync("I should see the activation section", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
    await testRunner.AndAsync("I should see the user search field", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("I should see the activation settings form", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin can search for a user by email in activation section")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminCanSearchForAUserByEmailInActivationSection()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can search for a user by email in activation section", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 62
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.AndAsync("I search for user \"customer5@gmail.com\" in the user search", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.ThenAsync("I should see the user email \"customer5@gmail.com\" in the details", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
    await testRunner.AndAsync("I should see the account active until date picker", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin can set account active until date for a user")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminCanSetAccountActiveUntilDateForAUser()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can set account active until date for a user", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 71
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
    await testRunner.AndAsync("I search for user \"customer5@gmail.com\" in the user search", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.AndAsync("I set the account active until date to next year", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.AndAsync("I save the user settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.ThenAsync("I should see a success message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin can update activation prices")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminCanUpdateActivationPrices()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can update activation prices", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 79
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 80
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
    await testRunner.AndAsync("I set the monthly price to \"50\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("I set the yearly price to \"400\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.AndAsync("I save the activation settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
    await testRunner.ThenAsync("I should see a success message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin can update the IBAN")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminCanUpdateTheIBAN()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can update the IBAN", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 88
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 89
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 90
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 91
    await testRunner.AndAsync("I set the IBAN to \"SK31 1200 0000 1987 4263 7541\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.AndAsync("I save the activation settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
    await testRunner.ThenAsync("I should see a success message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin can update activation messages")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminCanUpdateActivationMessages()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin can update activation messages", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 96
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 97
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.AndAsync("I set the English activation message to \"Please transfer the amount to activate y" +
                        "our account.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
    await testRunner.AndAsync("I save the activation settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
    await testRunner.ThenAsync("I should see a success message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin sees live preview of activation page")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("admin")]
        public async global::System.Threading.Tasks.Task AdminSeesLivePreviewOfActivationPage()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "admin"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin sees live preview of activation page", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 104
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 105
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 106
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
    await testRunner.AndAsync("I set the monthly price to \"45\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
    await testRunner.AndAsync("I set the IBAN to \"CZ65 0800 0000 1920 0014 5399\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
    await testRunner.ThenAsync("the activation preview should show price \"45\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 110
    await testRunner.AndAsync("the activation preview should show the IBAN \"CZ65 0800 0000 1920 0014 5399\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Full activation flow - admin activates inactive customer")]
        [global::NUnit.Framework.CategoryAttribute("e2e")]
        [global::NUnit.Framework.CategoryAttribute("activation")]
        [global::NUnit.Framework.CategoryAttribute("lifecycle")]
        public async global::System.Threading.Tasks.Task FullActivationFlow_AdminActivatesInactiveCustomer()
        {
            string[] tagsOfScenario = new string[] {
                    "e2e",
                    "activation",
                    "lifecycle"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Full activation flow - admin activates inactive customer", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 115
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
  await this.FeatureBackgroundAsync();
#line hidden
#line 116
    await testRunner.GivenAsync("I am logged in as an admin", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
    await testRunner.WhenAsync("I navigate to the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
    await testRunner.AndAsync("I search for user \"customer5@gmail.com\" in the user search", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
    await testRunner.AndAsync("I set the account active until date to next year", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.AndAsync("I save the user settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
    await testRunner.ThenAsync("I should see a success message", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 122
    await testRunner.WhenAsync("I log out", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 123
    await testRunner.AndAsync("I log in as \"customer5@gmail.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
    await testRunner.AndAsync("I navigate to the bettings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 125
    await testRunner.ThenAsync("I should see the bettings page content", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
